// Mocks generated by Mockito 5.4.6 from annotations
// in soloforte_app/test/widget/auth/login_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soloforte_app/core/interfaces/service_interfaces.dart' as _i3;
import 'package:soloforte_app/features/auth/domain/auth_state.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthState_0 extends _i1.SmartFake implements _i2.AuthState {
  _FakeAuthState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthService extends _i1.Mock implements _i3.IAuthService {
  MockIAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.AuthState?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i2.AuthState?>.empty(),
          )
          as _i4.Stream<_i2.AuthState?>);

  @override
  _i4.Future<_i2.AuthState> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i4.Future<_i2.AuthState>.value(
              _FakeAuthState_0(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.AuthState>);

  @override
  _i4.Future<_i2.AuthState> register(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [name, email, password]),
            returnValue: _i4.Future<_i2.AuthState>.value(
              _FakeAuthState_0(
                this,
                Invocation.method(#register, [name, email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.AuthState>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.AuthState?> checkAuth() =>
      (super.noSuchMethod(
            Invocation.method(#checkAuth, []),
            returnValue: _i4.Future<_i2.AuthState?>.value(),
          )
          as _i4.Future<_i2.AuthState?>);

  @override
  _i4.Future<_i2.AuthState> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i4.Future<_i2.AuthState>.value(
              _FakeAuthState_0(this, Invocation.method(#signInWithGoogle, [])),
            ),
          )
          as _i4.Future<_i2.AuthState>);

  @override
  _i4.Future<_i2.AuthState> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i4.Future<_i2.AuthState>.value(
              _FakeAuthState_0(this, Invocation.method(#signInWithApple, [])),
            ),
          )
          as _i4.Future<_i2.AuthState>);

  @override
  _i4.Future<void> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetPassword(String? code, String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [code, newPassword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.AuthState> enterDemoMode() =>
      (super.noSuchMethod(
            Invocation.method(#enterDemoMode, []),
            returnValue: _i4.Future<_i2.AuthState>.value(
              _FakeAuthState_0(this, Invocation.method(#enterDemoMode, [])),
            ),
          )
          as _i4.Future<_i2.AuthState>);
}
