// Mocks generated by Mockito 5.4.6 from annotations
// in soloforte_app/test/unit/services/report_data_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soloforte_app/features/harvests/data/harvest_repository.dart'
    as _i5;
import 'package:soloforte_app/features/harvests/domain/harvest_model.dart'
    as _i6;
import 'package:soloforte_app/features/ndvi/data/services/sentinel_service.dart'
    as _i9;
import 'package:soloforte_app/features/occurrences/domain/entities/occurrence.dart'
    as _i4;
import 'package:soloforte_app/features/occurrences/domain/repositories/occurrence_repository.dart'
    as _i2;
import 'package:soloforte_app/features/visits/domain/entities/visit.dart'
    as _i8;
import 'package:soloforte_app/features/visits/domain/repositories/visit_repository.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OccurrenceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOccurrenceRepository extends _i1.Mock
    implements _i2.OccurrenceRepository {
  MockOccurrenceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Occurrence>> getOccurrences() =>
      (super.noSuchMethod(
            Invocation.method(#getOccurrences, []),
            returnValue: _i3.Future<List<_i4.Occurrence>>.value(
              <_i4.Occurrence>[],
            ),
          )
          as _i3.Future<List<_i4.Occurrence>>);

  @override
  _i3.Future<_i4.Occurrence?> getOccurrenceById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getOccurrenceById, [id]),
            returnValue: _i3.Future<_i4.Occurrence?>.value(),
          )
          as _i3.Future<_i4.Occurrence?>);

  @override
  _i3.Future<void> createOccurrence(_i4.Occurrence? occurrence) =>
      (super.noSuchMethod(
            Invocation.method(#createOccurrence, [occurrence]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateOccurrence(_i4.Occurrence? occurrence) =>
      (super.noSuchMethod(
            Invocation.method(#updateOccurrence, [occurrence]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteOccurrence(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOccurrence, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [HarvestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHarvestRepository extends _i1.Mock implements _i5.HarvestRepository {
  MockHarvestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.Harvest>> getHarvests() =>
      (super.noSuchMethod(
            Invocation.method(#getHarvests, []),
            returnValue: _i3.Future<List<_i6.Harvest>>.value(<_i6.Harvest>[]),
          )
          as _i3.Future<List<_i6.Harvest>>);

  @override
  _i3.Future<_i6.Harvest?> getHarvestById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getHarvestById, [id]),
            returnValue: _i3.Future<_i6.Harvest?>.value(),
          )
          as _i3.Future<_i6.Harvest?>);

  @override
  _i3.Future<void> saveHarvest(_i6.Harvest? harvest) =>
      (super.noSuchMethod(
            Invocation.method(#saveHarvest, [harvest]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [VisitRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVisitRepository extends _i1.Mock implements _i7.VisitRepository {
  MockVisitRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveVisit(_i8.Visit? visit) =>
      (super.noSuchMethod(
            Invocation.method(#saveVisit, [visit]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.Visit>> getVisits() =>
      (super.noSuchMethod(
            Invocation.method(#getVisits, []),
            returnValue: _i3.Future<List<_i8.Visit>>.value(<_i8.Visit>[]),
          )
          as _i3.Future<List<_i8.Visit>>);

  @override
  _i3.Future<_i8.Visit?> getActiveVisit() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveVisit, []),
            returnValue: _i3.Future<_i8.Visit?>.value(),
          )
          as _i3.Future<_i8.Visit?>);

  @override
  _i3.Future<_i8.Visit?> getVisitById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVisitById, [id]),
            returnValue: _i3.Future<_i8.Visit?>.value(),
          )
          as _i3.Future<_i8.Visit?>);
}

/// A class which mocks [SentinelService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSentinelService extends _i1.Mock implements _i9.SentinelService {
  MockSentinelService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> authenticate() =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> searchImages({
    required List<double>? bbox,
    required DateTime? startDate,
    required DateTime? endDate,
    double? maxCloudCover = 20.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchImages, [], {
              #bbox: bbox,
              #startDate: startDate,
              #endDate: endDate,
              #maxCloudCover: maxCloudCover,
            }),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<_i10.Uint8List> fetchNDVIImage({
    required List<double>? bbox,
    Map<String, dynamic>? geometry,
    required DateTime? date,
    required int? width,
    required int? height,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNDVIImage, [], {
              #bbox: bbox,
              #geometry: geometry,
              #date: date,
              #width: width,
              #height: height,
            }),
            returnValue: _i3.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
          )
          as _i3.Future<_i10.Uint8List>);

  @override
  _i3.Future<Map<String, dynamic>> fetchStatistics({
    required Map<String, dynamic>? geoJsonGeometry,
    DateTime? date,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchStatistics, [], {
              #geoJsonGeometry: geoJsonGeometry,
              #date: date,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
